nelmio_api_doc:
    documentation:
        info:
            title: Travel API
            description: This is an API to gather informations about cool places in the world
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
